version: "3.7"

services:
  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "ark-admin"
      POSTGRES_PASSWORD: "dbpassword"
      POSTGRES_USER: "admin"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
volumes:
  db_data:
