[package]
name = "ark-metadata-marketplace"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.19"
aws-config = "1.1.9"
aws-sdk-s3 = "1.21.0"
dotenv = "0.15.0"
regex = "1.9.6"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
tracing = "0.1"
tracing-log = "0.2.0"
sha256 = "1.4.0"
aws-sdk-secretsmanager = "1.30.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow.workspace = true
arkproject.workspace = true
async-trait.workspace = true
tokio.workspace = true
starknet.workspace = true
sqlx.workspace = true

[dev-dependencies]
sqlx = { version = "0.7", features = [
    "postgres",
    "runtime-tokio-rustls",
    "tls-rustls",
] }
