[workspace.package]
name = "ark-services"
version = "0.1.0"
authors = ["Screenshot Labs", "Starknet community"]
license = "MIT OR Apache-2.0"
readme = "README.md"
#documentation = "https://docs.rs/..."
repository = "https://github.com/ArkProjectNFTs/ark-services"
homepage = "https://arkproject.dev"
edition = "2021"

[workspace]
members = [
  "ark-indexer",
  "lambdas/lambda-dynamo-common",
  "lambdas/apigw/lambda-http-common",
  "lambdas/apigw/lambda-get-collection",
  "lambdas/apigw/lambda-get-token",
  "lambdas/apigw/lambda-get-token-events",
]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0"
async-trait = "0.1.73"
tokio = { version = "1", features = ["full"] }
serde = "1.0.160"
serde_json = "1.0.96"
serde_with = "2.3.2"
thiserror = "1.0.40"
lambda-http-common = { path = "lambdas/apigw/lambda-http-common" }
lambda-dynamo-common = { path = "lambdas/lambda-dynamo-common" }
