#!/bin/sh

## This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask starknet-sequencer-adapter.service > /dev/null || true

systemctl daemon-reload > /dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled starknet-sequencer-adapter.service
then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
    deb-systemd-helper enable starknet-sequencer-adapter.service > /dev/null || true
    deb-systemd-helper enable starknet-sequencer-adapter > /dev/null || true

	deb-systemd-invoke start starknet-sequencer-adapter
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state starknet-sequencer-adapter.service > /dev/null || true
fi
