name: "Apply Marketplace SQL Migrations"
description: "Run SQL migrations on Mainnet database"
inputs:
  discord-webhook-url:
    description: "Discord webhook URL for notifications"
    required: true
  database-url:
    description: "Database URL for running migrations"
    required: true
  database-name:
    description: "Database name for notifications"
    required: true

runs:
  using: "composite"
  steps:
    - name: Notify start of migrations
      shell: bash
      run: |
        curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"content\": \"🗃️ Running SQL migrations from './ark-sqlx/migrations/marketplace' on ${{ inputs.database-name }} database...\"}" \
            ${{ inputs.discord-webhook-url }}

    - name: Install Dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y jq unzip curl
        # Install AWS CLI v2
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
        rm awscliv2.zip
        # Install sqlx-cli
        cargo install sqlx-cli --no-default-features --features rustls,postgres

    - name: Check Migration Files
      shell: bash
      run: |
        MIGRATION_PATH="./ark-sqlx/migrations/marketplace"
        if [ ! -d "$MIGRATION_PATH" ]; then
          echo "Migration directory does not exist at $MIGRATION_PATH"
          exit 1
        fi
        if [ -z "$(ls -A $MIGRATION_PATH)" ]; then
          echo "No migration files found in $MIGRATION_PATH"
          exit 1
        fi

    - name: Run SQL Migrations
      shell: bash
      run: |
        echo "::add-mask::${{ inputs.database-url }}"
        cd ark-sqlx
        sqlx migrate run --source ./migrations/marketplace
      env:
        DATABASE_URL: ${{ inputs.database-url }}

    - name: Notify success of migrations
      shell: bash
      if: success()
      run: |
        curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"content\": \"✅ SQL migrations from './ark-sqlx/migrations/marketplace' on ${{ inputs.database-name }} database were successful.\"}" \
            ${{ inputs.discord-webhook-url }}

    - name: Notify failure of migrations
      shell: bash
      if: failure()
      run: |
        curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"content\": \"❌ SQL migrations from './ark-sqlx/migrations/marketplace' on ${{ inputs.database-name }} database failed.\"}" \
            ${{ inputs.discord-webhook-url }}
