[package]
name = "ark-indexer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
dotenv = "0.15.0"
tokio.workspace = true
starknet = "0.5.0"
arkproject = { path = "/home/remi/apps/ArkIndexer" }