#!/bin/sh
set -e

## This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask ark-indexer-transactions-staging.service > /dev/null || true
systemctl daemon-reload

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled ark-indexer-transactions-staging.service
then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable ark-indexer-transactions-staging.service > /dev/null || true
	systemctl enable ark-indexer-transactions-staging.service
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state ark-indexer-transactions-staging.service > /dev/null || true
fi