name: "Discord Notification"
description: "Send a notification to a Discord channel"
inputs:
  discord-webhook-url:
    description: "Discord webhook URL for notifications"
    required: true
  message:
    description: "Message to send to the Discord channel"
    required: true
runs:
  using: "composite"
  steps:
    - name: Send notification to Discord channel
      shell: bash
      run: |
        curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"content\": \"${{ inputs.message }}\"}" \
            ${{ inputs.discord-webhook-url }}
