name: Deploy Arkchain Indexer to AWS (Staging)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/deploy-arkchain-indexer-staging.yml"
      - "infrastructure/cdk-ark-ecr/**"
      - "infrastructure/cdk-arkchain-indexers/**"

jobs:

  push-indexer-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install pnpm
        run: |
          npm install -g pnpm
          npm install -g aws-cdk

      - name: Build indexer, tag, and push image to Amazon ECR
        run: |
          docker buildx create --use --name ecr-deploy-builder-arkchain-indexer
          docker buildx build --tag $ECR_URL:arkchain-indexer-staging-latest --file docker/arkchain-indexer/Dockerfile . --load
          docker push $ECR_URL:arkchain-indexer-staging-latest
        env:
          ECR_URL: ${{ env.ECR_URL }}
          RPC_PROVIDER: ${{ secrets.RPC_PROVIDER }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_CDK_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_CDK_SECRET_ACCESS_KEY }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_CDK_ACCOUNT_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
