name: Deploy NFT APIs (Staging)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/deploy-ark-redis.yml"
      - "infrastructure/cdk-ark-redis/**"

jobs:
  discord-notification:
    runs-on: ubuntu-latest
    name: Discord Notification
    steps:
      - name: Send notification to dev-updates channel
        run: |
          curl -H "Content-Type: application/json" \
              -X POST \
              -d '{
                  "content": "🧪 Deploying NFT APIs on Staging environment..."
              }' \
              ${{ secrets.DISCORD_WEBHOOK_URL }}

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install pnpm
        run: |
          npm install -g pnpm
          npm install -g aws-cdk

      - name: Install Dependencies
        run: |
          cd infrastructure/cdk-ark-api
          pnpm install

      - name: Deploy Redis
        run: |
          cd infrastructure/cdk-ark-api
          pnpm cdk deploy --require-approval never
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_CDK_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets. AWS_CDK_SECRET_ACCESS_KEY }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_CDK_ACCOUNT_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
