name: Update ECS Task Definition

on:
  workflow_dispatch:

jobs:
  task-definition:
    runs-on: ubuntu-latest
    name: Handling Release
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Render Amazon ECS task definition
        id: render-web-container
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: "infrastructure/ecs/indexer-mainnet.json"
          container-name: "ark_indexer"
          image: "${{ steps.login-ecr.outputs.registry }}/arkproject:${{ github.event.release.tag_name }}"

      - name: Add environment variables to ECS task definition
        id: add-env-var
        uses: cvmaker-bv/amazon-ecs-task-environment@v1
        env:
          ARK_INDEXER_VERSION: "v0.0.1"
          RPC_PROVIDER: "https://juno.mainnet.arkproject.dev"
          IPFS_GATEWAY_URI: "https://ipfs.arkproject.dev"
          RUST_LOG: "trace"
        with:
          task-definition: ${{ steps.render-web-container.outputs.task-definition }}
          container-name: "ark_indexer"
          env-variables: "${{ toJson(env) }}"

      - name: Deploy to Amazon ECS service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.add-env-var.outputs.task-definition }}
          service: "ark-indexer-mainnet"
          cluster: "ark-indexers"
