name: Lint & Code Quality Checks

on:
  push:
    branches:
      - main
    paths:
      - "ark-indexer/**"
      - "ark-sqlx/**"
      - "arkchain-indexer/**"
  pull_request:
    paths:
      - "ark-indexer/**"
      - "ark-sqlx/**"
      - "arkchain-indexer/**"
env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Cargo Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Cache Cargo Dependencies
        uses: Swatinem/rust-cache@v2

      - name: Set Up Stable Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Run Cargo Check
        uses: actions-rs/cargo@v1
        with:
          command: check

  lints:
    name: Run Lints
    runs-on: ubuntu-latest
    env:
      SQLX_OFFLINE: true
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Cache Cargo Dependencies
        uses: Swatinem/rust-cache@v2

      - name: Set Up Stable Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy

      - name: Run Cargo Format Check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run Cargo Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
