name: MKT CRON (Production) (Scaleway)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/marketplace-cron-production.yml"
      - "ark-marketplace-cron/**"
      - "docker/marketplace-cron/**"

jobs:
  discord-notification:
    runs-on: ubuntu-latest
    name: Discord Notification
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Send notification to dev-updates channel
        run: |
          curl -H "Content-Type: application/json" \
              -X POST \
              -d '{
                  "content": "🚢 Building and pushing Marketplace Cron to Scaleway Registry..."
              }' \
              ${{ secrets.DISCORD_WEBHOOK_URL }}

  push-marketplace-cron-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Login to Scaleway Registry
        uses: docker/login-action@v1
        with:
          registry: rg.fr-par.scw.cloud
          username: nologin
          password: ${{ secrets.SCW_SECRET_KEY }}

      - name: Build cron, tag, and push image to Scaleway Registry
        run: |
          docker buildx create --use --name marketplace-cron
          docker buildx build --tag rg.fr-par.scw.cloud/namespace-ark-project/marketplace-cron:latest --file docker/marketplace-cron/Dockerfile . --load
          docker push rg.fr-par.scw.cloud/namespace-ark-project/marketplace-cron:latest

  discord-notification-success:
    needs: push-marketplace-cron-image
    runs-on: ubuntu-latest
    name: Discord Notification Success
    steps:
      - name: Send success notification to dev-updates channel
        run: |
          curl -H "Content-Type: application/json" \
              -X POST \
              -d '{
                  "content": "✅ Marketplace Cron successfully built and pushed to Scaleway Registry!"
              }' \
              ${{ secrets.DISCORD_WEBHOOK_URL }}
