name: MKT SQL Migrations (Scaleway)

on:
  workflow_dispatch:

jobs:
  run-migrations:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [mainnet]

    name: Run SQL Migrations on ${{ matrix.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Apply Marketplace SQL Migrations
        uses: ./.github/actions/marketplace-sql-migrations
        with:
          aws-access-key-id: ${{ secrets.AWS_CDK_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_CDK_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          secret-id: "prod/ark-db-credentials"
