name: MKT Metadata Indexer (Production) (Mainnet) (AWS)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/marketplace-metadata-indexer-production.yml"
      - "infrastructure/cdk-ark-metadata-marketplace/**"
      - "ark-metadata-marketplace/**"

jobs:
  discord-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Send notification to dev-updates channel
        uses: ./.github/actions/discord-notification
        with:
          discord-webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: "🚀 Deploying Metadata Marketplace Indexer on Production environment..."

  deploy-marketplace-metadata-indexer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Cache Cargo registry
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Cache Cargo Dependencies
        uses: Swatinem/rust-cache@v2

      - name: Cache Cargo target dir
        uses: actions/cache@v2
        with:
          path: target
          key: ${{ runner.os }}-target-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-target-

      - name: Build ark-metadata-marketplace
        run: cargo build --release -p ark-metadata-marketplace

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.STARKNET_NODE_MAINNET_SSH_KEY }}

      - name: Apply Marketplace SQL Migrations
        uses: ./.github/actions/marketplace-sql-migrations
        with:
          discord-webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          database-url: ${{ secrets.DATABASE_URL }}
          database-name: production

      - name: Ensure deployment directory exists
        run: ssh -o StrictHostKeyChecking=no github@${{ vars.STARKNET_NODE_MAINNET_SERVER_IP }} "mkdir -p /opt/marketplace-metadata-indexer"

      - name: Stop the service
        continue-on-error: true
        run: ssh -o StrictHostKeyChecking=no github@${{ vars.STARKNET_NODE_MAINNET_SERVER_IP }} "sudo systemctl stop marketplace-metadata-indexer.service"

      - name: Upload binary to Scaleway server
        run: scp -o StrictHostKeyChecking=no target/release/ark-metadata-marketplace github@${{ vars.STARKNET_NODE_MAINNET_SERVER_IP }}:/opt/marketplace-metadata-indexer/

      - name: Restart the service
        run: ssh -o StrictHostKeyChecking=no github@${{ vars.STARKNET_NODE_MAINNET_SERVER_IP }} "sudo systemctl start marketplace-metadata-indexer.service"
