name: Release Workflow

on:
  release:
    types: [published]

jobs:
  release-job:
    runs-on: ubuntu-latest
    name: Handling Release
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # ... Other steps ...

      - name: Build, Tag, and Push Docker Image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: arkproject
          TAG: ${{ github.event.release.tag_name }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$TAG -f Dockerfile .
          docker push $REGISTRY/$REPOSITORY:$TAG
      
      - name: Notify Discord
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content":"A new release has been published: '${{ github.event.release.tag_name }}'. \nRelease Link: '${{ github.event.release.html_url }}'"}' \
               ${{ secrets.DISCORD_WEBHOOK_URL }}