name: Release Workflow

on:
  release:
    types: [published]

jobs:
  push-docker-image:
    runs-on: ubuntu-latest
    name: Push Docker Image
    env:
      AWS_REGION: us-east-1
      REPOSITORY: arkproject
      TAG: ${{ github.event.release.tag_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.5.5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1.3.3

      - name: Build, Tag, and Push Docker Image to Amazon ECR
        env:
          INDEXER_AWS_ACCESS_KEY_ID: ${{ secrets.INDEXER_AWS_ACCESS_KEY_ID }}
          INDEXER_AWS_SECRET_ACCESS_KEY: ${{ secrets.INDEXER_AWS_SECRET_ACCESS_KEY }}
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/${{ env.REPOSITORY }}:${{ env.TAG }} --build-arg AWS_ACCESS_KEY_ID=${{ secrets.INDEXER_AWS_ACCESS_KEY_ID }} --build-arg AWS_SECRET_ACCESS_KEY=${{ secrets.INDEXER_AWS_SECRET_ACCESS_KEY }} -f Dockerfile .
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.REPOSITORY }}:${{ env.TAG }}

  update-task-definition:
    needs: push-docker-image
    runs-on: ubuntu-latest
    name: Update ECS Task Definitions
    strategy:
      matrix:
        environment: [mainnet, testnet] # Define your environments here
    env:
      AWS_REGION: us-east-1
      REPOSITORY: arkproject
      TAG: ${{ github.event.release.tag_name }}
      CONTAINER_NAME: ark_indexer
      SERVICE_NAME: ark-indexer-${{ matrix.environment }}
      CLUSTER_NAME: ark-indexers
      TASK_DEFINITION_FILE: infrastructure/ecs/indexer-${{ matrix.environment }}.json
      INDEXER_TABLE_NAME: ark_project_${{ matrix.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.5.5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1.3.3

      - name: Update Amazon ECS task definition
        id: render-web-container
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: "${{ env.TASK_DEFINITION_FILE }}"
          container-name: "${{ env.CONTAINER_NAME }}"
          image: "${{ steps.login-ecr.outputs.registry }}/${{ env.REPOSITORY }}:${{ env.TAG }}"

      - name: Add environment variables to ECS task definition
        id: add-env-var
        uses: cvmaker-bv/amazon-ecs-task-environment@v1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.INDEXER_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.INDEXER_AWS_SECRET_ACCESS_KEY }}
          INDEXER_VERSION: ${{ github.event.release.tag_name }}
          RPC_PROVIDER: ${{ matrix.environment == 'mainnet' && secrets.RPC_PROVIDER_MAINNET || secrets.RPC_PROVIDER_TESTNET }}
          IPFS_GATEWAY_URI: "https://ipfs.arkproject.dev"
          RUST_LOG: "info"
          HEAD_OF_CHAIN: "true"
        with:
          task-definition: ${{ steps.render-web-container.outputs.task-definition }}
          container-name: "${{ env.CONTAINER_NAME }}"
          env-variables: "${{ toJson(env) }}"

      - name: Deploy to Amazon ECS service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.add-env-var.outputs.task-definition }}
          service: "${{ env.SERVICE_NAME }}"
          cluster: "${{ env.CLUSTER_NAME }}"

  discord-notification:
    needs: "update-task-definition"
    runs-on: ubuntu-latest
    name: Discord Notification
    steps:
      - name: Send notification to dev-updates channel
        run: |
          curl -H "Content-Type: application/json" \
              -X POST \
              --data "{\"content\":\"🔗 A new release has been published (ark-services): ${env.TAG}.\
              \n\n*Changelog:*\n${{ github.event.release.body }}\"}" \
              ${{ secrets.DISCORD_WEBHOOK_URL }}
