name: Continuous Integration

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  create-tag:
    name: Create and Push Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Create and Push New Tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
